// AI-slop analyzer: finds artifacts LLMs commonly leave behind in code.

import { isCodeFile, isConfigFile, isMarkdownFile, README_MAX_BYTES } from '../walker.js';

const PATTERNS = [
  {
    id: 'ai-confession',
    label: 'AI confession in comments',
    weight: 5,
    cap: 10,
    re: /\b(?:as an ai\b|i am an ai\b|as a language model|i cannot (?:assist|help|provide)|i'?m sorry, but i can'?t)\b/i,
    why: 'LLM refusal/disclaimer text pasted straight into the codebase.',
  },
  {
    id: 'llm-placeholder',
    label: 'LLM placeholder comments',
    weight: 4,
    cap: 8,
    re: /\/\/\s*(?:your code here|implementation (?:goes|here)|rest of the (?:code|implementation)|\.\.\.\s*(?:remaining|rest)\b)|#\s*(?:your code here|implementation (?:goes|here))/i,
    why: 'Classic ChatGPT artifact — the "implementation" never arrived.',
  },
  {
    id: 'vibe-naming',
    label: 'Copium variable names',
    weight: 1,
    cap: 4,
    re: /\b(?:const|let|var)\s+(?:temp|test|foo|bar|baz|data1?|stuff|thing|helper)\d?\s*=/,
    why: 'Generic temp/test/foo naming survives when nobody reviewed the diff.',
  },
  {
    id: 'debug-logging',
    label: 'Leftover debug logging',
    weight: 1,
    cap: 6,
    re: /^\s*(?:console\.log|print|fmt\.Println|System\.out\.println|dbg!)\s*\(/m,
    why: 'Debug output shipped to production.',
  },
  {
    id: 'todo-spam',
    label: 'Unfinished TODO/FIXME/HACK',
    weight: 1,
    cap: 6,
    re: /(?:\/\/|#|\/\*|;)\s*(?:TODO|FIXME|HACK|XXX)\b/,
    why: 'A promise the author never kept.',
  },
  {
    id: 'lazy-error-handling',
    label: 'Silent error swallowing',
    weight: 3,
    cap: 8,
    re: /\/\/\s*ignore\b|catch\s*\(\s*\w*\s*\)\s*\{\s*\}|except\s*(?:\w*)?\s*:\s*(?:pass\b|\.\.\.)/,
    why: 'Errors vanish here. Debugging this in prod is a horror movie.',
  },
  {
    id: 'generated-header',
    label: '"Generated by Copilot/AI" headers',
    weight: 3,
    cap: 6,
    re: /(?:generated (?:by|with) (?:github )?(?:copilot|chatgpt|claude|ai)\b|written by (?:an )?ai\b)/i,
    why: 'The code is telling on itself.',
  },
  {
    id: 'debugger-leftover',
    label: 'debugger statement shipped',
    weight: 3,
    cap: 6,
    re: /^\s*debugger\s*;?\s*$/m,
    why: 'A breakpoint made it to production. Nobody read this diff.',
  },
  {
    id: 'guessy-comment',
    label: 'Hedging comments',
    weight: 1,
    cap: 4,
    re: /(?:\/\/|#)\s*(?:not sure (?:why|if)|this might (?:work|break)|i think this|probably (?:works|fine)|seems to work)\b/i,
    why: 'If the author isn\'t sure why it works, nobody is.',
  },
];

// Character names LLMs love in sample data
const SAMPLE_DATA_RE = /["'](?:John Doe|Jane Doe|Foo Bar|Lorem ipsum|example@example\.com|test@test\.com)["']/;

export function analyzeSlop(files) {
  const findings = [];
  const perPattern = new Map();

  for (const file of files) {
    if (!isCodeFile(file.path) || isConfigFile(file.path)) continue;
    // Docs with prose (READMEs, SKILL.md) trip false positives on hedging
    // phrases. Only scan small ones — big READMEs are documentation, not code.
    if (isMarkdownFile(file.path) && file.size > README_MAX_BYTES) continue;
    const lines = file.content.split('\n');

    for (const pat of PATTERNS) {
      const used = perPattern.get(pat.id) || 0;
      if (used >= pat.cap) continue;
      for (let i = 0; i < lines.length; i++) {
        if (pat.re.test(lines[i])) {
          findings.push({
            rule: pat.id,
            file: file.path,
            line: i + 1,
            excerpt: lines[i].trim().slice(0, 100),
            weight: pat.weight,
          });
          perPattern.set(pat.id, (perPattern.get(pat.id) || 0) + 1);
          break; // one hit per pattern per file is enough signal
        }
      }
    }

    if (SAMPLE_DATA_RE.test(file.content)) {
      findings.push({
        rule: 'sample-data',
        file: file.path,
        line: null,
        excerpt: 'John Doe / Lorem ipsum / test@test.com sample data',
        weight: 2,
      });
    }
  }

  const rawPenalty = findings.reduce((s, f) => s + f.weight, 0);
  const topRules = PATTERNS
    .filter((p) => perPattern.has(p.id))
    .map((p) => ({ id: p.id, label: p.label, why: p.why, hits: perPattern.get(p.id) }));

  return {
    id: 'slop',
    label: 'AI Slop',
    score: Math.min(40, rawPenalty),
    max: 40,
    findings,
    summary: topRules,
  };
}
