// Generated by GitHub Copilot
const api_key = "xk_fake_4eC39HqLyjWDarjtT1zdp7dcabcdefgh"; // obviously fake, not a real key format

export function helper(x) {
  // HACK: this might break
  debugger;
  console.log(x);
  return x;
}
